# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed67415b6b700bba97ed0a1be53fd5fac04712bb7e09ef5d578a6d89ff2cb65d7af241d7401376edf045f69e95dffa2f955b0a5ad73e77ca332d39eb78dbba6d

test:
  secret_key_base: 4e94d57f41d99bb981446a60364224d21b2eb165353813c7e21409f46ee56635cf84a1dac028fb00ca4b3626feaba61783a61be41e0c884eb67f12c4fb3acc5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
